### ISSUE TITLE
A Great Article!

### ISSUE THREAD

**Issue by invictus717** [hzwer/WritingAIPaper#1]
This article is super constructive, and I would like to thank the great contributions of the authors. And I personally suggest the authors can submit it to some journato for possible publication or arxiv preprints.

**Comment by hzwer** [comment]
I submitted it to arxiv, but they seem not to accept such topics. The current form also seems suitable for a blog post.

**Comment by invictus717** [comment]
Arxiv even announces jokes, you can double-check this, hahahahaha

**Comment by George121380** [comment]
Super inspiring article for new researchers like me! Thanks for your sharing!
